In [ ]:
!pip install numpy

In [ ]:
import numpy as np

# New section

In [ ]:
my_lst = [1,2,3,4]
np.array(my_lst)

array([1, 2, 3, 4])

In [ ]:
lst.ndim

2

In [ ]:
my_lst = [[1,2,3,4],[5,6,7,8]]
lst = np.array(my_lst)
lst

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
type(lst)

numpy.ndarray

In [ ]:
lst.ndim

2

In [ ]:
lst.shape

(2, 4)

In [ ]:
lst1=[1,2,3,6]
lst2=[2,5,8,7]
lst3=[7,6,4,5]

f_lst=np.array([lst1,lst2,lst3])
f_lst

array([[1, 2, 3, 6],
       [2, 5, 8, 7],
       [7, 6, 4, 5]])

In [ ]:
f_lst.shape

(3, 4)

In [ ]:
g=f_lst.reshape(2,6)
g

array([[1, 2, 3, 6, 2, 5],
       [8, 7, 7, 6, 4, 5]])

In [ ]:
g.shape

(2, 6)

In [ ]:
f_lst.reshape(4,3)

array([[1, 2, 3],
       [6, 2, 5],
       [8, 7, 7],
       [6, 4, 5]])

In [ ]:
f_lst.shape

(3, 4)

In [ ]:
arr=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr[2]

np.int64(3)

In [ ]:
f=np.array([[1, 2, 3],
       [6, 2, 5],
       [8, 7, 7],
       [6, 4, 5]])

In [ ]:
#indexing
f[:,:]

array([[1, 2, 3],
       [6, 2, 5],
       [8, 7, 7],
       [6, 4, 5]])

In [ ]:
f[:,1]

array([2, 2, 7, 4])

In [ ]:
#f[:,1:]

array([[2, 3],
       [2, 5],
       [7, 7],
       [4, 5]])

In [ ]:
f[0:2,1:]

array([[2, 3],
       [2, 5]])

In [ ]:
f[0:2,0:]

array([[1, 2, 3],
       [6, 2, 5]])

In [ ]:
f[2:,1:]

array([[7, 7],
       [4, 5]])

In [ ]:
#inbuilt function
#arange- to arrange in lower to upper nums
f=np.arange(0,12)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#arange takes range from 0 to 12 and takes another attribute as steps 2
f=np.arange(0,12,2)
f

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#to get equally divided points by the linspace() can be used sometimes for points initialization
k=np.linspace(1,20,50)
k

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [ ]:
#copy function and broadcasting (from the third index chnage to 500)
# array is refernce type if changing this array will have chnaged the upper array in which reference is given to
r_arr=k

In [ ]:
r_arr[3:]=500
print(r_arr)

[  1.        100.          1.7755102 500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.       ]


In [ ]:
## array is refernce type by changing this array will have changed the upper array in which reference is given to
print(k)

[  1.        100.          1.7755102 500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.        500.        500.        500.        500.
 500.        500.       ]


In [ ]:
#to print this referncing we can use the copy function this prevents the arr to refernce creates another memory space for another array to store
arr1=k.copy()

In [ ]:
#print(arr1)
arr1[3:]=1000
#print(arr1)


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#checks for the condition given
val = 2
arr<val

array([ True, False, False, False, False, False, False, False])

In [ ]:
val = 2
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16])